In [6]:
"""
Titanic Data Analysis and JSON Export
Author: [Markus von Aschoff]
Description: Analyze Titanic passenger data, engineer features, and export to JSON
"""
 
import pandas as pd
import numpy as np
import json
from pathlib import Path
 
# Set up paths
DATA_DIR = Path("data")
CSV_FILE = DATA_DIR / "titanic.csv"
JSON_FILE = DATA_DIR / "titanic_data.json"
 
# Create data directory if it doesn't exist
DATA_DIR.mkdir(exist_ok=True)
 
print("Project setup complete!")
print(f"Data directory: {DATA_DIR}")
print(f"CSV file location: {CSV_FILE}")

Project setup complete!
Data directory: data
CSV file location: data/titanic.csv

In [7]:
# Load the dataset
df = pd.read_csv(CSV_FILE)

print(f"Dataset loaded successfully! Shape: {df.shape}")
print(f"\nColumns: {list(df.columns)}")
print(f"\nFirst few rows:")
df.head()

Dataset loaded successfully! Shape: (891, 12)

Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

First few rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
print("=" * 55)
print("DESCRIPTIVE STATISTICS")
print("=" * 55)

# Select numeric columns only (exclude PassengerId and Survived – they are IDs/labels)
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()
numeric_columns = [c for c in numeric_columns if c not in ["PassengerId", "Survived"]]

stats_rows = []
for col in numeric_columns:
    stats_rows.append({
        "Column":   col,
        "Mean":     round(df[col].mean(),   4),
        "Median":   round(df[col].median(), 4),
        "Std Dev":  round(df[col].std(),    4),
        "Min":      round(df[col].min(),    4),
        "Max":      round(df[col].max(),    4),
    })

stats_df = pd.DataFrame(stats_rows).set_index("Column")
print(stats_df.to_string())
stats_df

=======================================================
DESCRIPTIVE STATISTICS
=======================================================
           Mean   Median  Std Dev   Min       Max
Column
Pclass   2.3086   3.0000   0.8361  1.00    3.0000
Age     29.6991  28.0000  14.5265  0.42   80.0000
SibSp    0.5230   0.0000   1.1027  0.00    8.0000
Parch    0.3816   0.0000   0.8061  0.00    6.0000
Fare    32.2042  14.4542  49.6934  0.00  512.3292

           Mean   Median  Std Dev   Min       Max
Column
Pclass   2.3086   3.0000   0.8361  1.00    3.0000
Age     29.6991  28.0000  14.5265  0.42   80.0000
SibSp    0.5230   0.0000   1.1027  0.00    8.0000
Parch    0.3816   0.0000   0.8061  0.00    6.0000
Fare    32.2042  14.4542  49.6934  0.00  512.3292